#cloud-config
datasource:
  Ec2:
    strict_id: false

users:
  - name: ubuntu
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_key}

package_update: true
package_upgrade: true

packages:
  - docker.io
  - docker-compose
  - htop
  - curl
  - wget
  - unzip

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - getent group docker || groupadd docker # Создать группу docker, если не существует
  - usermod -aG docker ubuntu
  # Внимание: безопасность и доступ к портам обеспечиваются только через security groups Yandex Cloud
  # Запуск одного или нескольких контейнеров из Yandex Container Registry
  - |
    set -e  # Прерывать выполнение при ошибке
    echo "container_images: ${container_images}"
    echo "microservice_name: ${microservice_name}"

     # Логин в YCR (предполагается, что у ВМ есть роль images.puller)
    echo "Pulling image ${container_image}"
    docker pull ${container_image}

    # Останавливаем все предыдущие контейнеры, если есть
    if [ "$(docker ps -aq)" ]; then
      echo "Stopping all existing containers"
      docker rm -f $(docker ps -aq)
    fi
    # Запуск контейнера

    docker run -d --name ${microservice_name} --restart unless-stopped -p 80:80 ${container_image}
