#cloud-config
users:
  - name: ubuntu
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_key}

package_update: true
package_upgrade: true

packages:
  - docker.io
  - docker-compose
  - fail2ban
  - ufw
  - htop
  - curl
  - wget
  - unzip

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker ubuntu
  - systemctl enable fail2ban
  - systemctl start fail2ban
  - ufw --force enable
  - ufw allow 22/tcp
  - ufw allow 80/tcp
  - ufw allow 443/tcp
  # Запуск одного или нескольких контейнеров из Yandex Container Registry
  - |
    # Остановить и удалить все ранее запущенные контейнеры
    if [ "$(docker ps -aq)" ]; then
      echo "Stopping all existing containers"
      docker rm -f $(docker ps -aq)
    fi

    # Логин в YCR (предполагается, что у ВМ есть роль images.puller)
    IFS=',' read -ra imgs <<< "${container_images}"
    idx=0
    for img in "${imgs[@]}"; do
      echo "Pulling image $img"
      docker pull "$img"
      cname="${microservice_name}-${idx}"
      docker run -d --name "$cname" --restart unless-stopped "$img"
      idx=$((idx+1))
    done
